---
# vars file for ambari-config

# http://192.168.100.175
# repo_base_url: "http://{{ hostvars[groups.all[-1]]['ansible_host'] }}"
repo_base_url: "http://192.168.100.175"

# centos7
repo_os_family: "centos{{ ansible_distribution_major_version }}"

# redhat7
baseurl_os_family: "redhat{{ ansible_distribution_major_version }}"

# http://192.168.100.175/HDP/centos7/3.1.0.0-78
hdp_main_repo_url: "{{ repo_base_url }}/HDP/{{ repo_os_family }}/{{ hdp_version }}"

# http://192.168.100.175/HDP-GPL/centos7/3.1.0.0-78
gpl_repo_url: "{{ repo_base_url }}/HDP-GPL/{{ repo_os_family }}/{{ hdp_gpl_version }}"

# http://192.168.100.175/HDP-UTILS/centos7/1.1.0.22
utils_repo_url: "{{ repo_base_url }}/HDP-UTILS/{{ repo_os_family }}/{{ hdp_utils_version }}"
