---
- hosts: all
  tasks:
    - debug:
        msg: 'HELLO'
      with_items: "{{ groups.all }}"

    - lineinfile:
        path: /root/hosts
        regexp: "^{{ hostvars[item]['ansible_'~hostvars[item].ansible_default_ipv4.alias | regex_replace('-','_')]['ipv4']['address'] }}.*"
        line: "{{ hostvars[item]['ansible_'~hostvars[item].ansible_default_ipv4.alias | regex_replace('-','_')]['ipv4']['address'] }} {{ hostvars[item]['ansible_nodename'] }}"
        insertafter: "^127..*$"
        state: present
      with_items:
        - "{{ groups['all']|sort(reverse=True) }}"
