---
# tasks file for common
- name: Config Repositories - OS & Ambari
  include_tasks: repo.yml
  tags: 
    - config_repo

- name: Install Required Packages - {{ packages }}
  package:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items: "{{ packages }}"
  tags:
    - install_packages

- name: Stop and Disable the Firewall Service - {{ firewall_service_name }}
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items: "{{ firewall_service_name }}"
  ignore_errors: true
  tags:
    - disable_firewall

- name: Disable SElinux
  selinux:
    state: disabled
  tags:
    - disable_selinux

- name: Start and Enable the NTP Service - {{ ntp_service_name }}
  service:
    name: "{{ ntp_service_name }}"
    state: started
    enabled: yes
  tags: 
    - config_ntp

- name: Stop and Disable the New NTP Service - {{ ntp_service_name_2 }}
  service:
    name: "{{ ntp_service_name_2 }}"
    state: stopped
    enabled: no
  ignore_errors: true
  tags:
    - config_ntp

- name: Setting NTP Config - /etc/ntp.conf
  include_tasks: ntp_client.yml
  notify: 
    - restart_ntpd
  tags:
    - config_ntp

- name: Set TimeZone to - {{ timezone }}
  shell: timedatectl set-timezone {{ timezone }}
  notify: 
    - restart_ntpd
  tags:
    - config_ntp

- meta: flush_handlers

- name: Install JDK - {{ jdk }}
  include_tasks: jdk.yml
  tags:
    - install_jdk

- block:
    - name: Disable THP on Current System
      shell: echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag
    - name: Disable THP on System Startup - 1/2
      lineinfile:
        path: /etc/rc.d/rc.local
        line: 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'
        mode: 0755
    - name: Disable THP on System Startup - 1/2
      lineinfile:
        path: /etc/rc.d/rc.local
        line: 'echo never > /sys/kernel/mm/transparent_hugepage/defrag'
        mode: 0755
  tags: 
    - disable_thp

- name: Add Host Mapping to - /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "^{{ hostvars[item]['ansible_'~hostvars[item].ansible_default_ipv4.alias | regex_replace('-','_')]['ipv4']['address'] }}.*"
    line: "{{ hostvars[item]['ansible_'~hostvars[item].ansible_default_ipv4.alias | regex_replace('-','_')]['ipv4']['address'] }} {{ hostvars[item]['ansible_nodename'] }}"
    insertafter: "^127..*$"
    state: present
  with_items: "{{ groups['all']|sort(reverse=True) }}"
  tags:
    - config_hosts

- name: Create Limits Config Directory - /etc/security/limits.d
  file:
    path: /etc/security/limits.d
    mode: 0755
    state: directory
  tags:
    - tuned

- name: Set nofile and nproc limits
  blockinfile:
    path: /etc/security/limits.d/99-hadoop.conf
    create: yes
    mode: 0644
    block: |
      * soft nofile 32768
      * hard nofile 32768
      * soft nproc 32768
      * hard nproc 32768
      root       soft    nproc     unlimited
      ams        -       nofile   64000
      atlas      -       nofile   64000
      druid      -       nofile   64000
      hive       -       nofile   64000
      infra-solr -       nofile   64000
      kms        -       nofile   64000
      knox       -       nofile   64000
      logsearch  -       nofile   64000
      ranger     -       nofile   64000
      spark      -       nofile   64000
      zeppelin   -       nofile   64000
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  tags:
    - tuned

- name: Set swappiness to - {{ swappiness }}
  sysctl: 
    name: vm.swappiness
    value: "{{ swappiness }}"
    state: present
    reload: yes
    ignoreerrors: yes
  tags:
    - tuned

- name: Config System Tuning - /etc/tuned/hdp/tuned.conf
  import_tasks: tuned.yml
  tags:
    - tuned




